//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSRDDToken.Autenticacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Autenticacion.IAutenticacion")]
    public interface IAutenticacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/GetServerDate", ReplyAction="http://tempuri.org/IAutenticacion/GetServerDateResponse")]
        string GetServerDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/GetServerDate", ReplyAction="http://tempuri.org/IAutenticacion/GetServerDateResponse")]
        System.Threading.Tasks.Task<string> GetServerDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/Autentica", ReplyAction="http://tempuri.org/IAutenticacion/AutenticaResponse")]
        string Autentica();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/Autentica", ReplyAction="http://tempuri.org/IAutenticacion/AutenticaResponse")]
        System.Threading.Tasks.Task<string> AutenticaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutenticacionChannel : PSRDDToken.Autenticacion.IAutenticacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticacionClient : System.ServiceModel.ClientBase<PSRDDToken.Autenticacion.IAutenticacion>, PSRDDToken.Autenticacion.IAutenticacion {
        
        public AutenticacionClient() {
        }
        
        public AutenticacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetServerDate() {
            return base.Channel.GetServerDate();
        }
        
        public System.Threading.Tasks.Task<string> GetServerDateAsync() {
            return base.Channel.GetServerDateAsync();
        }
        
        public string Autentica() {
            return base.Channel.Autentica();
        }
        
        public System.Threading.Tasks.Task<string> AutenticaAsync() {
            return base.Channel.AutenticaAsync();
        }
    }
}
